CREATE TABLE cidade( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      estado_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE conta( 
      id  integer generated by default as identity     NOT NULL , 
      tipo_conta_id integer    NOT NULL , 
      cliente_id integer    NOT NULL , 
      natureza_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
      dt_emissao date    NOT NULL , 
      dt_vencimento date    NOT NULL , 
      valor float    NOT NULL , 
      desconto float   , 
      juros float   , 
      multa float   , 
      obs blob sub_type 1   , 
      quitada char  (1)    DEFAULT 'f'  NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE contato( 
      id  integer generated by default as identity     NOT NULL , 
      pessoa_id integer    NOT NULL , 
      email blob sub_type 1    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      telefone blob sub_type 1   , 
      obs blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado_negociacao( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      cor blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado_orcamento( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE estado_venda( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE grupo( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE historico_negociacao( 
      id  integer generated by default as identity     NOT NULL , 
      negociacao_id integer    NOT NULL , 
      tipo_contato_id integer    NOT NULL , 
      dt_contato timestamp    NOT NULL , 
      descricao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE natureza( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE negociacao( 
      id  integer generated by default as identity     NOT NULL , 
      cliente_id integer    NOT NULL , 
      vendedor_id integer    NOT NULL , 
      origem_negociacao_id integer    NOT NULL , 
      tipo_negociacao_id integer    NOT NULL , 
      estado_negociacao_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
      dt_inicio_negociacao timestamp    NOT NULL , 
      dt_fim_negociacao timestamp   , 
      descricao blob sub_type 1    NOT NULL , 
      obs blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE negociacao_produto( 
      id  integer generated by default as identity     NOT NULL , 
      produto_id integer    NOT NULL , 
      negociacao_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE orcamento( 
      id  integer generated by default as identity     NOT NULL , 
      cliente_id integer    NOT NULL , 
      vendedor_id integer    NOT NULL , 
      estado_orcamento_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
      dt_orcamento timestamp    NOT NULL , 
      obs blob sub_type 1   , 
      frete float   , 
      valor_total float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE orcamento_item( 
      id  integer generated by default as identity     NOT NULL , 
      orcamento_id integer    NOT NULL , 
      produto_id integer    NOT NULL , 
      quantidade float    NOT NULL , 
      valor float    NOT NULL , 
      desconto float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE origem_negociacao( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa( 
      id  integer generated by default as identity     NOT NULL , 
      system_user_id integer   , 
      nome blob sub_type 1    NOT NULL , 
      documento blob sub_type 1    NOT NULL , 
      obs blob sub_type 1   , 
      fone blob sub_type 1   , 
      email blob sub_type 1   , 
      cidade_id integer    NOT NULL , 
      rua blob sub_type 1   , 
      numero blob sub_type 1   , 
      bairro blob sub_type 1   , 
      complemento blob sub_type 1   , 
      cep blob sub_type 1   , 
      dt_ativacao date    NOT NULL , 
      dt_desativacao date   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE pessoa_grupo( 
      id  integer generated by default as identity     NOT NULL , 
      grupo_id integer    NOT NULL , 
      pessoa_id integer    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE produto( 
      id  integer generated by default as identity     NOT NULL , 
      unidade_id integer    NOT NULL , 
      tipo_produto_id integer    NOT NULL , 
      fornecedor_id integer    NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
      dt_cadastro date    NOT NULL , 
      cod_barras blob sub_type 1   , 
      preco_custo float    NOT NULL , 
      preco_venda float    NOT NULL , 
      peso_liquido float    NOT NULL , 
      peso_bruto float    NOT NULL , 
      estoque_minimo float    NOT NULL , 
      estoque_maximo float    NOT NULL , 
      qtde_estoque float    NOT NULL , 
      obs blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE prospeccao( 
      id  integer generated by default as identity     NOT NULL , 
      vendedor_id integer    NOT NULL , 
      cliente_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
      horario_inicial timestamp    NOT NULL , 
      horario_final timestamp    NOT NULL , 
      titulo blob sub_type 1   , 
      cor blob sub_type 1   , 
      observacao blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_conta( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_contato( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_negociacao( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE tipo_produto( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE unidade( 
      id  integer generated by default as identity     NOT NULL , 
      nome blob sub_type 1    NOT NULL , 
 PRIMARY KEY (id)) ; 

CREATE TABLE venda( 
      id  integer generated by default as identity     NOT NULL , 
      cliente_id integer    NOT NULL , 
      vendedor_id integer    NOT NULL , 
      estado_venda_id integer    NOT NULL , 
      system_unit_id integer    NOT NULL , 
      dt_venda timestamp    NOT NULL , 
      obs blob sub_type 1   , 
      frete float   , 
      valor_total float   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE venda_item( 
      id  integer generated by default as identity     NOT NULL , 
      produto_id integer    NOT NULL , 
      venda_id integer    NOT NULL , 
      quantidade float    NOT NULL , 
      valor float    NOT NULL , 
      desconto float   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE cidade ADD CONSTRAINT fk_cidade_1 FOREIGN KEY (estado_id) references estado(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_3 FOREIGN KEY (natureza_id) references natureza(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_2 FOREIGN KEY (cliente_id) references pessoa(id); 
ALTER TABLE conta ADD CONSTRAINT fk_conta_1 FOREIGN KEY (tipo_conta_id) references tipo_conta(id); 
ALTER TABLE contato ADD CONSTRAINT fk_contato_1 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE historico_negociacao ADD CONSTRAINT fk_historico_negociacao_2 FOREIGN KEY (tipo_contato_id) references tipo_contato(id); 
ALTER TABLE historico_negociacao ADD CONSTRAINT fk_historico_negociacao_1 FOREIGN KEY (negociacao_id) references negociacao(id); 
ALTER TABLE negociacao ADD CONSTRAINT fk_negociacao_5 FOREIGN KEY (tipo_negociacao_id) references tipo_negociacao(id); 
ALTER TABLE negociacao ADD CONSTRAINT fk_negociacao_4 FOREIGN KEY (origem_negociacao_id) references origem_negociacao(id); 
ALTER TABLE negociacao ADD CONSTRAINT fk_negociacao_3 FOREIGN KEY (vendedor_id) references pessoa(id); 
ALTER TABLE negociacao ADD CONSTRAINT fk_negociacao_1 FOREIGN KEY (cliente_id) references pessoa(id); 
ALTER TABLE negociacao ADD CONSTRAINT fk_negociacao_6 FOREIGN KEY (estado_negociacao_id) references estado_negociacao(id); 
ALTER TABLE negociacao_produto ADD CONSTRAINT fk_negociacao_produto_2 FOREIGN KEY (negociacao_id) references negociacao(id); 
ALTER TABLE negociacao_produto ADD CONSTRAINT fk_negociacao_produto_1 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE orcamento ADD CONSTRAINT fk_orcamento_3 FOREIGN KEY (vendedor_id) references pessoa(id); 
ALTER TABLE orcamento ADD CONSTRAINT fk_orcamento_2 FOREIGN KEY (estado_orcamento_id) references estado_orcamento(id); 
ALTER TABLE orcamento ADD CONSTRAINT fk_orcamento_1 FOREIGN KEY (cliente_id) references pessoa(id); 
ALTER TABLE orcamento_item ADD CONSTRAINT fk_orcamento_item_2 FOREIGN KEY (produto_id) references produto(id); 
ALTER TABLE orcamento_item ADD CONSTRAINT fk_orcamento_item_1 FOREIGN KEY (orcamento_id) references orcamento(id); 
ALTER TABLE pessoa ADD CONSTRAINT fk_pessoa_1 FOREIGN KEY (cidade_id) references cidade(id); 
ALTER TABLE pessoa_grupo ADD CONSTRAINT fk_pessoa_grupo_2 FOREIGN KEY (pessoa_id) references pessoa(id); 
ALTER TABLE pessoa_grupo ADD CONSTRAINT fk_pessoa_grupo_1 FOREIGN KEY (grupo_id) references grupo(id); 
ALTER TABLE produto ADD CONSTRAINT fk_produto_3 FOREIGN KEY (fornecedor_id) references pessoa(id); 
ALTER TABLE produto ADD CONSTRAINT fk_produto_2 FOREIGN KEY (tipo_produto_id) references tipo_produto(id); 
ALTER TABLE produto ADD CONSTRAINT fk_produto_1 FOREIGN KEY (unidade_id) references unidade(id); 
ALTER TABLE prospeccao ADD CONSTRAINT fk_prospeccao_2 FOREIGN KEY (vendedor_id) references pessoa(id); 
ALTER TABLE prospeccao ADD CONSTRAINT fk_prospeccao_1 FOREIGN KEY (cliente_id) references pessoa(id); 
ALTER TABLE venda ADD CONSTRAINT fk_venda_3 FOREIGN KEY (vendedor_id) references pessoa(id); 
ALTER TABLE venda ADD CONSTRAINT fk_venda_2 FOREIGN KEY (estado_venda_id) references estado_venda(id); 
ALTER TABLE venda ADD CONSTRAINT fk_venda_1 FOREIGN KEY (cliente_id) references pessoa(id); 
ALTER TABLE venda_item ADD CONSTRAINT fk_venda_item_2 FOREIGN KEY (venda_id) references venda(id); 
ALTER TABLE venda_item ADD CONSTRAINT fk_venda_item_1 FOREIGN KEY (produto_id) references produto(id); 
